#pragma once

#include "presets.hpp"

namespace aja {
static const RoutingPresetMap kSDIDisplayYCbCrPresets = {
	{"SD_ST352_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  0,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { false, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::SD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::SD_ST352,
	  VPIDStandard_483_576}},
	{"HD_720p_ST292_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  0,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { false, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_720p_ST292,
	  VPIDStandard_720}},
	{"HD_1080_ST292_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  0,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { false, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080_ST292,
	  VPIDStandard_1080}},
	{"HD_1080_ST372_Dual_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  2,
	  2,
	  0,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch2}][0]",
	  {},
	  // { false, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080_ST372_Dual,
	  VPIDStandard_1080_DualLink}},
	{"HD_720p_ST425_3Ga_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  kEnable3GOut,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_720p_ST425_3Ga,
	  VPIDStandard_720_3Ga}},
	{"HD_1080p_ST425_3Ga_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  kEnable3GOut,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080p_ST425_3Ga,
	  VPIDStandard_1080_3Ga}},
	{"HD_1080p_ST425_3Gb_DL_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  (kEnable3GOut | kConvert3GIn | kConvert3GOut | kConvert3GaRGBOut),
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { true, false, false, true, true, false, true, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080p_ST425_3Gb_DL,
	  VPIDStandard_1080_DualLink_3Gb}},
	{"HD_720p_ST425_3Gb_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  2,
	  kEnable3GOut,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch1}][1];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_720p_ST425_3Gb,
	  VPIDStandard_720_3Gb}},
	{"HD_1080p_ST425_3Gb_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  2,
	  kEnable3GOut,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch1}][1];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080p_ST425_3Gb,
	  VPIDStandard_1080_3Gb}},
	{"HD_1080p_ST425_Dual_3Ga_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  2,
	  2,
	  kEnable3GOut,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch1}][1];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080p_ST425_Dual_3Ga,
	  VPIDStandard_1080_Dual_3Ga}},
	{"HD_1080p_ST425_Dual_3Gb_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  2,
	  2,
	  kEnable3GOut,
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch1}][1];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, false },
	  RasterDefinition::HD,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::HD_1080p_ST425_Dual_3Gb,
	  VPIDStandard_1080_Dual_3Gb}},
	{"UHD4K_ST292_Quad_1_5_Squares_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable3GbOut | kEnable4KQuads),
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch2}][0];"
	  "fb[{ch3}][0]->sdi[{ch3}][0];"
	  "fb[{ch4}][0]->sdi[{ch4}][0];",
	  {},
	  // { false, false, false, false, false, false, false, true, false, false },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST292_Quad_1_5_Squares,
	  VPIDStandard_1080}},
	{"UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable3GOut | kEnable3GbOut),
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch2}][0];"
	  "fb[{ch3}][0]->sdi[{ch3}][0];"
	  "fb[{ch4}][0]->sdi[{ch4}][0];",
	  {},
	  // { true, false, false, false, false, false, false, true, false, false },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST425_Quad_3Ga_Squares,
	  VPIDStandard_1080_3Ga}},
	{"UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable3GOut | kEnable3GbOut),
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];"
	  "fb[{ch2}][0]->sdi[{ch2}][0];"
	  "fb[{ch3}][0]->sdi[{ch3}][0];"
	  "fb[{ch4}][0]->sdi[{ch4}][0];",
	  {},
	  // { true, false, false, false, false, false, false, true, false, false },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST425_Quad_3Gb_Squares,
	  VPIDStandard_1080_DualLink_3Gb}},
	{"UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  2,
	  2,
	  (kEnable3GOut | kEnable4KTSI),
	  false,
	  "fb[{ch1}][0]->tsi[{ch1}][0];"
	  "fb[{ch1}][1]->tsi[{ch1}][1];"
	  "fb[{ch2}][0]->tsi[{ch2}][0];"
	  "fb[{ch2}][1]->tsi[{ch2}][1];"
	  "tsi[{ch1}][0]->sdi[{ch1}][0];"
	  "tsi[{ch1}][1]->sdi[{ch1}][1];"
	  "tsi[{ch2}][0]->sdi[{ch2}][0];"
	  "tsi[{ch2}][1]->sdi[{ch2}][1];",
	  {},
	  // { true, false, false, false, false, false, true, false, false, true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST425_Dual_3Gb_2SI,
	  VPIDStandard_2160_DualLink}},
	{"UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable3GOut | kEnable4KTSI),
	  false,
	  "fb[{ch1}][0]->tsi[{ch1}][0];"
	  "fb[{ch1}][1]->tsi[{ch1}][1];"
	  "fb[{ch2}][0]->tsi[{ch2}][0];"
	  "fb[{ch2}][1]->tsi[{ch2}][1];"
	  "tsi[{ch1}][0]->sdi[{ch1}][0];"
	  "tsi[{ch1}][1]->sdi[{ch2}][0];"
	  "tsi[{ch2}][0]->sdi[{ch3}][0];"
	  "tsi[{ch2}][1]->sdi[{ch4}][0];",
	  {},
	  // { true, false, false, false, false, false, false, false, false, true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST425_Quad_3Ga_2SI,
	  VPIDStandard_2160_QuadLink_3Ga}},
	{"UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable3GOut | kConvert3GaRGBOut | kEnable4KTSI),
	  false,
	  "fb[{ch1}][0]->tsi[{ch1}][0];"
	  "fb[{ch1}][1]->tsi[{ch1}][1];"
	  "fb[{ch2}][0]->tsi[{ch2}][0];"
	  "fb[{ch2}][1]->tsi[{ch2}][1];"
	  "tsi[{ch1}][0]->sdi[{ch1}][0];"
	  "tsi[{ch1}][1]->sdi[{ch2}][0];"
	  "tsi[{ch2}][0]->sdi[{ch3}][0];"
	  "tsi[{ch2}][1]->sdi[{ch4}][0];",
	  {},
	  // { true,false,false,false,false,false,true,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST425_Quad_3Gb_2SI,
	  VPIDStandard_2160_QuadDualLink_3Gb}},
	{"UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  (kEnable6GOut | kEnable4KTSI),
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { false,true,false,false,false,false,false,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST2018_6G_Squares_2SI,
	  VPIDStandard_2160_Single_6Gb}},
	{"UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display (Kona5/io4K+)",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable6GOut | kEnable4KTSI),
	  false,
	  "fb[{ch3}][0]->tsi[{ch3}][0];"
	  "fb[{ch3}][1]->tsi[{ch3}][1];"
	  "fb[{ch4}][0]->tsi[{ch4}][0];"
	  "fb[{ch4}][1]->tsi[{ch4}][1];"
	  "tsi[{ch3}][0]->sdi[{ch1}][0];"
	  "tsi[{ch3}][1]->sdi[{ch2}][0];"
	  "tsi[{ch4}][0]->sdi[{ch3}][0];"
	  "tsi[{ch4}][1]->sdi[{ch4}][0];",
	  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
	  // { false,true,false,false,false,false,false,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST2018_6G_Squares_2SI,
	  VPIDStandard_2160_Single_6Gb}},
	{"UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  1,
	  1,
	  (kEnable12GOut | kEnable4KTSI),
	  false,
	  "fb[{ch1}][0]->sdi[{ch1}][0];",
	  {},
	  // { false,false,true,false,false,true,false,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST2018_12G_Squares_2SI,
	  VPIDStandard_2160_Single_12Gb}},
	{"UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display (Kona5/io4K+)",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable12GOut | kConvert3GOut | kEnable4KTSI),
	  false,
	  "fb[{ch3}][0]->tsi[{ch3}][0];"
	  "fb[{ch3}][1]->tsi[{ch3}][1];"
	  "fb[{ch4}][0]->tsi[{ch4}][0];"
	  "fb[{ch4}][1]->tsi[{ch4}][1];"
	  "tsi[{ch3}][0]->sdi[{ch1}][0];"
	  "tsi[{ch3}][1]->sdi[{ch2}][0];"
	  "tsi[{ch4}][0]->sdi[{ch3}][0];"
	  "tsi[{ch4}][1]->sdi[{ch4}][0];",
	  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
	  // { false,false,true,false,false,true,false,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD4K_ST2018_12G_Squares_2SI,
	  VPIDStandard_2160_Single_12Gb}},
	// TODO
	{"UHD28K_ST2082_Dual_12G_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  2,
	  2,
	  (kEnable12GOut | kConvert3GOut | kEnable4KTSI),
	  false,
	  "",
	  {},
	  // { false,false,true,false,false,true,false,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD28K_ST2082_Dual_12G,
	  VPIDStandard_4320_DualLink_12Gb}},
	// TODO
	{"UHD28K_ST2082_Quad_12G_YCbCr_Display",
	 {kConnectionKindSDI,
	  NTV2_MODE_DISPLAY,
	  4,
	  4,
	  (kEnable12GOut | kConvert3GOut | kEnable4KTSI),
	  false,
	  "",
	  {},
	  // { false,false,true,false,false,true,false,false,false,true },
	  RasterDefinition::UHD_4K,
	  HDMIWireFormat::Unknown,
	  SDIWireFormat::UHD28K_ST2082_Quad_12G,
	  VPIDStandard_4320_QuadLink_12Gb}},
};
} // aja
