#include "aja-common.hpp"
#include "aja-routing.hpp"

#include <ajantv2/includes/ntv2devicefeatures.h>
#include <ajantv2/includes/ntv2utils.h>

namespace aja {

#define ENUM_CASE_RETURN_STRING(enum_name) \
	case (enum_name):                  \
		return #enum_name
std::string RoutingPresetIDString(RoutingPresetID id)
{
	switch (id) {
		ENUM_CASE_RETURN_STRING(AJA_RP_CAP_HDMI_ONE_WIRE);
		ENUM_CASE_RETURN_STRING(HDMI_HD_HFR_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_RGB_Capture_io4KPlus);
		ENUM_CASE_RETURN_STRING(AJA_RP_OUT_HDMI_ONE_WIRE_RGB);
		ENUM_CASE_RETURN_STRING(HDMI_LFR_RGB_Display_TTapPro);
		ENUM_CASE_RETURN_STRING(HDMI_HFR_RGB_Display_TTapPro);
		ENUM_CASE_RETURN_STRING(HDMI_HD_LFR_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_YCbCr_Capture_io4KPlus);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(AJA_RP_OUT_HDMI_ONE_WIRE_YCBCR);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_LFR_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_LFR_YCbCr_Display_Kona5_8K);
		ENUM_CASE_RETURN_STRING(HDMI_HD_LFR_YCbCr_Display_TTapPro);
		ENUM_CASE_RETURN_STRING(HDMI_HD_HFR_YCbCr_Display_TTapPro);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_LFR_YCbCr_Display_TTapPro);
		ENUM_CASE_RETURN_STRING(HDMI_UHD_4K_HFR_YCbCr_Display_TTapPro);
		ENUM_CASE_RETURN_STRING(HD_720p_ST292_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080_ST292_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080_ST372_Dual_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_720p_ST425_3Ga_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Ga_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_DL_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_720p_ST425_3Gb_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_Dual_3Ga_RGB_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_Dual_3Gb_RGB_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Ga_Squares_RGB_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Gb_Squares_RGB_Capture);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Ga_2SI_RGB_Capture);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Gb_2SI_RGB_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_6G_Squares_2SI_RGB_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_6G_Squares_2SI_RGB_Capture_Kona5_io4KPlus);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_12G_Squares_2SI_RGB_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_12G_Squares_2SI_RGB_Capture_Kona5_io4KPlus);
		ENUM_CASE_RETURN_STRING(HD_720p_ST292_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_1080_ST292_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_1080_ST372_Dual_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_720p_ST425_3Ga_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Ga_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_DL_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_720p_ST425_3Gb_RGB_Display);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_RGB_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Gb_Squares_RGB_Display);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Ga_2SI_RGB_Display);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Gb_2SI_RGB_Display);
		ENUM_CASE_RETURN_STRING(AJA_RP_CAP_SDI_SINGLE_SD_HD_YCBCR);
		ENUM_CASE_RETURN_STRING(HD_1080_ST372_Dual_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_DL_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(HD_720p_ST425_3Gb_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_Dual_3Ga_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_Dual_3Gb_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST292_Quad_1_5_Squares_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_6G_Squares_2SI_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_6G_Squares_2SI_YCbCr_Capture_Kona5_io4KPlus);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_12G_Squares_2SI_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_12G_Squares_2SI_YCbCr_Capture_Kona5_io4KPlus);
		ENUM_CASE_RETURN_STRING(UHD28K_ST2082_Dual_12G_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(UHD28K_ST2082_Quad_12G_YCbCr_Capture);
		ENUM_CASE_RETURN_STRING(AJA_RP_OUT_SDI_SINGLE_SD_HD_YCBCR);
		ENUM_CASE_RETURN_STRING(HD_1080_ST372_Dual_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(AJA_RP_OUT_SDI_3Ga_HD_YCBCR);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_3Gb_DL_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(AJA_RP_OUT_SDI_3GbDS_HD_YCBCR);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_Dual_3Ga_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(HD_1080p_ST425_Dual_3Gb_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST292_Quad_1_5_Squares_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display_Kona5_io4KPlus);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(
			UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display_Kona5_io4KPlus);
		ENUM_CASE_RETURN_STRING(UHD28K_ST2082_Dual_12G_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(UHD28K_ST2082_Quad_12G_YCbCr_Display);
		ENUM_CASE_RETURN_STRING(AJA_RP_INVALID);
	}
	return "";
}

void RoutingManager::build_preset_table()
{
	static const RoutingPresetMap kRoutingPresets = {
		/*
		 * HDMI RGB Capture
		 */
		{AJA_RP_CAP_HDMI_ONE_WIRE,
		 {AJA_RP_CAP_HDMI_ONE_WIRE,
		  ConnectionKind::HDMI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD, RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {},
		  true,
		  "hdmi[{ch1}][0]->fb[{ch1}][0];"}},
		{HDMI_UHD_4K_RGB_Capture_io4KPlus,
		 {HDMI_UHD_4K_RGB_Capture_io4KPlus,
		  ConnectionKind::HDMI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_IO4KPLUS},
		  true,
		  "hdmi[{ch1}][4]->tsi[{ch1}][0];"
		  "hdmi[{ch1}][5]->tsi[{ch1}][1];"
		  "hdmi[{ch1}][6]->tsi[{ch2}][0];"
		  "hdmi[{ch1}][7]->tsi[{ch2}][1];"
		  "tsi[{ch1}][2]->fb[{ch1}][0];"
		  "tsi[{ch1}][3]->fb[{ch1}][1];"
		  "tsi[{ch2}][2]->fb[{ch2}][0];"
		  "tsi[{ch2}][3]->fb[{ch2}][1];"}},
		/*
		 * HDMI RGB Display
		 */
		{AJA_RP_OUT_HDMI_ONE_WIRE_RGB,
		 {AJA_RP_OUT_HDMI_ONE_WIRE_RGB,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::SD, RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {},
		  true,
		  "fb[{ch1}][2]->hdmi[0][0];"}},
		{HDMI_LFR_RGB_Display_TTapPro,
		 {HDMI_LFR_RGB_Display_TTapPro,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_TTAP_PRO},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"
		  "fb[{ch1}][2]->hdmi[{ch1}][0];"}},
		{HDMI_HFR_RGB_Display_TTapPro,
		 {HDMI_HFR_RGB_Display_TTapPro,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kConvert3GaRGBOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_TTAP_PRO},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"
		  "fb[{ch1}][2]->hdmi[{ch1}][0];"}},
		/*
		 * HDMI YCbCr Capture
		 */
		{HDMI_HD_LFR_YCbCr_Capture,
		 {HDMI_HD_LFR_YCbCr_Capture,
		  ConnectionKind::HDMI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {},
		  false,
		  "hdmi[{ch1}][0]->fb[{ch1}][0];"}},
		{HDMI_UHD_4K_YCbCr_Capture_io4KPlus,
		 {HDMI_UHD_4K_YCbCr_Capture_io4KPlus,
		  ConnectionKind::HDMI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_IO4KPLUS},
		  false,
		  "hdmi[{ch1}][0]->tsi[{ch1}][0];"
		  "hdmi[{ch1}][1]->tsi[{ch1}][1];"
		  "hdmi[{ch1}][2]->tsi[{ch2}][0];"
		  "hdmi[{ch1}][3]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		{HDMI_UHD_4K_YCbCr_Capture,
		 {HDMI_UHD_4K_YCbCr_Capture,
		  ConnectionKind::HDMI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {},
		  false,
		  "hdmi[{ch1}][0]->tsi[{ch1}][0];"
		  "hdmi[{ch1}][1]->tsi[{ch1}][1];"
		  "hdmi[{ch1}][2]->tsi[{ch2}][0];"
		  "hdmi[{ch1}][3]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		/*
		 * HDMI YCbCr Display
		 */
		{AJA_RP_OUT_HDMI_ONE_WIRE_YCBCR,
		 {AJA_RP_OUT_HDMI_ONE_WIRE_YCBCR,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {},
		  false,
		  "fb[{ch1}][0]->hdmi[0][0];"}},
		{HDMI_UHD_4K_LFR_YCbCr_Display,
		 {HDMI_UHD_4K_LFR_YCbCr_Display,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  2,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {},
		  false,
		  "fb[{ch1}][0]->tsi[{ch1}][0];"
		  "fb[{ch1}][1]->tsi[{ch1}][1];"
		  "fb[{ch2}][0]->tsi[{ch2}][0];"
		  "fb[{ch2}][1]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->hdmi[0][0];"
		  "tsi[{ch1}][1]->hdmi[0][1];"
		  "tsi[{ch2}][0]->hdmi[0][2];"
		  "tsi[{ch2}][1]->hdmi[0][3];"}},
		{HDMI_UHD_4K_LFR_YCbCr_Display_Kona5_8K,
		 {HDMI_UHD_4K_LFR_YCbCr_Display_Kona5_8K,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_KONA5_8K},
		  false,
		  "fb[{ch1}][0]->hdmi[0][0];"}},
		{HDMI_HD_LFR_YCbCr_Display_TTapPro,
		 {HDMI_HD_LFR_YCbCr_Display_TTapPro,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_TTAP_PRO},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch1}][0]->hdmi[{ch1}][0];"}},
		{HDMI_HD_HFR_YCbCr_Display_TTapPro,
		 {HDMI_HD_HFR_YCbCr_Display_TTapPro,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_TTAP_PRO},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch1}][0]->hdmi[{ch1}][0];"}},
		{HDMI_UHD_4K_LFR_YCbCr_Display_TTapPro,
		 {HDMI_UHD_4K_LFR_YCbCr_Display_TTapPro,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable4KTSI | kEnable6GOut,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_TTAP_PRO},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch1}][0]->hdmi[{ch1}][0];"}},
		{HDMI_UHD_4K_HFR_YCbCr_Display_TTapPro,
		 {HDMI_UHD_4K_HFR_YCbCr_Display_TTapPro,
		  ConnectionKind::HDMI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable4KTSI | kEnable12GOut,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_Unknown},
		  {DEVICE_ID_TTAP_PRO},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch1}][0]->hdmi[{ch1}][0];"}},
		/*
		 * SDI RGB Capture
		 */
		{HD_720p_ST292_RGB_Capture,
		 {HD_720p_ST292_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_720},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_1080_ST292_RGB_Capture,
		 {HD_1080_ST292_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_1080_ST372_Dual_RGB_Capture,
		 {HD_1080_ST372_Dual_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch2}][0]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_720p_ST425_3Ga_RGB_Capture,
		 {HD_720p_ST425_3Ga_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Ga},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_1080p_ST425_3Ga_RGB_Capture,
		 {HD_1080p_ST425_3Ga_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_3Ga},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_1080p_ST425_3Gb_DL_RGB_Capture,
		 {HD_1080p_ST425_3Gb_DL_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_720p_ST425_3Gb_RGB_Capture,
		 {HD_720p_ST425_3Gb_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Gb},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_1080p_ST425_3Gb_RGB_Capture,
		 {HD_1080p_ST425_3Gb_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_3Gb},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{HD_1080p_ST425_Dual_3Ga_RGB_Capture,
		 {HD_1080p_ST425_Dual_3Ga_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_Dual_3Ga},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"
		  "dli[{ch2}][0]->fb[{ch2}][0];"}},
		{HD_1080p_ST425_Dual_3Gb_RGB_Capture,
		 {HD_1080p_ST425_Dual_3Gb_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kConvert3GIn,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_Dual_3Gb},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"
		  "dli[{ch2}][0]->fb[{ch2}][0];"}},
		{UHD4K_ST425_Quad_3Ga_Squares_RGB_Capture,
		 {UHD4K_ST425_Quad_3Ga_Squares_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_3Ga},
		  {},
		  true,
		  // SDIs -> Dual-Links
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "sdi[{ch3}][0]->dli[{ch3}][0];"
		  "sdi[{ch3}][1]->dli[{ch3}][1];"
		  "sdi[{ch4}][0]->dli[{ch4}][0];"
		  "sdi[{ch4}][1]->dli[{ch4}][1];" // Dual-Links -> Framestores
		  "dli[{ch1}][0]->fb[{ch1}][0];"
		  "dli[{ch2}][0]->fb[{ch2}][0];"
		  "dli[{ch3}][0]->fb[{ch3}][0];"
		  "dli[{ch4}][0]->fb[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Gb_Squares_RGB_Capture,
		 {UHD4K_ST425_Quad_3Gb_Squares_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  true,
		  // SDIs -> Dual-Links
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "sdi[{ch3}][0]->dli[{ch3}][0];"
		  "sdi[{ch3}][1]->dli[{ch3}][1];"
		  "sdi[{ch4}][0]->dli[{ch4}][0];"
		  "sdi[{ch4}][1]->dli[{ch4}][1];" // Dual-Links -> Framestores
		  "dli[{ch1}][0]->fb[{ch1}][0];"
		  "dli[{ch2}][0]->fb[{ch2}][0];"
		  "dli[{ch3}][0]->fb[{ch3}][0];"
		  "dli[{ch4}][0]->fb[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Ga_2SI_RGB_Capture,
		 {UHD4K_ST425_Quad_3Ga_2SI_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadLink_3Ga},
		  {},
		  true,
		  // SDIs -> Dual-Links
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "sdi[{ch3}][0]->dli[{ch3}][0];"
		  "sdi[{ch3}][1]->dli[{ch3}][1];"
		  "sdi[{ch4}][0]->dli[{ch4}][0];"
		  "sdi[{ch4}][1]->dli[{ch4}][1];" // Dual-Links -> TSI Mux
		  "dli[{ch1}][0]->tsi[{ch1}][0];"
		  "dli[{ch2}][0]->tsi[{ch1}][1];"
		  "dli[{ch3}][0]->tsi[{ch2}][0];"
		  "dli[{ch4}][0]->tsi[{ch2}][1];" // TSI Mux -> Framestores
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		{UHD4K_ST425_Quad_3Gb_2SI_RGB_Capture,
		 {UHD4K_ST425_Quad_3Gb_2SI_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable3GOut | kEnable3GbOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadDualLink_3Gb},
		  {},
		  true,
		  // SDIs -> Dual-Links
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "sdi[{ch3}][0]->dli[{ch3}][0];"
		  "sdi[{ch3}][1]->dli[{ch3}][1];"
		  "sdi[{ch4}][0]->dli[{ch4}][0];"
		  "sdi[{ch4}][1]->dli[{ch4}][1];" // Dual-Links -> TSI Mux
		  "dli[{ch1}][0]->tsi[{ch1}][0];"
		  "dli[{ch2}][0]->tsi[{ch1}][1];"
		  "dli[{ch3}][0]->tsi[{ch2}][0];"
		  "dli[{ch4}][0]->tsi[{ch2}][1];" // TSI Mux -> Framestores
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},

		/////////////////////////////////
		{UHD4K_ST2018_6G_Squares_2SI_RGB_Capture,
		 {UHD4K_ST2018_6G_Squares_2SI_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_6Gb},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{UHD4K_ST2018_6G_Squares_2SI_RGB_Capture_Kona5_io4KPlus,
		 {UHD4K_ST2018_6G_Squares_2SI_RGB_Capture_Kona5_io4KPlus,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_6Gb},
		  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "sdi[{ch3}][0]->dli[{ch3}][0];"
		  "sdi[{ch3}][1]->dli[{ch3}][1];"
		  "sdi[{ch4}][0]->dli[{ch4}][0];"
		  "sdi[{ch4}][1]->dli[{ch4}][1];"
		  "dli[{ch1}][0]->tsi[{ch1}][0];"
		  "dli[{ch2}][0]->tsi[{ch1}][1];"
		  "dli[{ch3}][0]->tsi[{ch2}][0];"
		  "dli[{ch4}][0]->tsi[{ch2}][1];"
		  "tsi[{ch1}][2]->fb[{ch1}][0];"
		  "tsi[{ch1}][3]->fb[{ch1}][1];"
		  "tsi[{ch2}][2]->fb[{ch2}][0];"
		  "tsi[{ch2}][3]->fb[{ch2}][1];"}},
		{UHD4K_ST2018_12G_Squares_2SI_RGB_Capture,
		 {UHD4K_ST2018_12G_Squares_2SI_RGB_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_12Gb},
		  {},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "dli[{ch1}][0]->fb[{ch1}][0];"}},
		{UHD4K_ST2018_12G_Squares_2SI_RGB_Capture_Kona5_io4KPlus,
		 {UHD4K_ST2018_12G_Squares_2SI_RGB_Capture_Kona5_io4KPlus,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_12Gb},
		  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
		  true,
		  "sdi[{ch1}][0]->dli[{ch1}][0];"
		  "sdi[{ch1}][1]->dli[{ch1}][1];"
		  "sdi[{ch2}][0]->dli[{ch2}][0];"
		  "sdi[{ch2}][1]->dli[{ch2}][1];"
		  "sdi[{ch3}][0]->dli[{ch3}][0];"
		  "sdi[{ch3}][1]->dli[{ch3}][1];"
		  "sdi[{ch4}][0]->dli[{ch4}][0];"
		  "sdi[{ch4}][1]->dli[{ch4}][1];"
		  "dli[{ch1}][0]->tsi[{ch1}][0];"
		  "dli[{ch2}][0]->tsi[{ch1}][1];"
		  "dli[{ch3}][0]->tsi[{ch2}][0];"
		  "dli[{ch4}][0]->tsi[{ch2}][1];"
		  "tsi[{ch1}][2]->fb[{ch1}][0];"
		  "tsi[{ch1}][3]->fb[{ch1}][1];"
		  "tsi[{ch2}][2]->fb[{ch2}][0];"
		  "tsi[{ch2}][3]->fb[{ch2}][1];"}},
		/////////////////////////////////
		/*
		 * SDI RGB Display
		 */
		{HD_720p_ST292_RGB_Display,
		 {HD_720p_ST292_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_720},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}[0];"
		  "dlo[{ch1}][1]->sdi[{ch2}][0];"}},
		{HD_1080_ST292_RGB_Display,
		 {HD_1080_ST292_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}[0];"
		  "dlo[{ch1}][1]->sdi[{ch2}][0];"}},
		{HD_1080_ST372_Dual_RGB_Display,
		 {HD_1080_ST372_Dual_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  2,
		  1,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}[0];"
		  "dlo[{ch1}][1]->sdi[{ch2}][0];"}},
		{HD_720p_ST425_3Ga_RGB_Display,
		 {HD_720p_ST425_3Ga_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut | kConvert3GaRGBOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Ga},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"}},
		{HD_1080p_ST425_3Ga_RGB_Display,
		 {HD_1080p_ST425_3Ga_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut | kConvert3GaRGBOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_3Ga},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"}},
		{HD_1080p_ST425_3Gb_DL_RGB_Display,
		 {HD_1080p_ST425_3Gb_DL_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut | kEnable3GbOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"}},
		{HD_720p_ST425_3Gb_RGB_Display,
		 {HD_720p_ST425_3Gb_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  2,
		  kEnable3GOut | kEnable3GbOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Gb},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"}},
		{HD_1080p_ST425_3Gb_RGB_Display,
		 {HD_1080p_ST425_3Gb_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  2,
		  kEnable3GOut | kEnable3GbOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_3Gb},
		  {},
		  true,
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"}},
		{UHD4K_ST425_Quad_3Gb_Squares_RGB_Display,
		 {UHD4K_ST425_Quad_3Gb_Squares_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kEnable3GbOut | kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  true,
		  // Framestores -> Dual-Links
		  "fb[{ch1}][2]->dlo[{ch1}][0];"
		  "fb[{ch2}][2]->dlo[{ch2}][0];"
		  "fb[{ch3}][2]->dlo[{ch3}][0];"
		  "fb[{ch4}][2]->dlo[{ch4}][0];" // Dual-Links -> SDIs
		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"
		  "dlo[{ch2}][0]->sdi[{ch2}][0];"
		  "dlo[{ch2}][1]->sdi[{ch2}][1];"
		  "dlo[{ch3}][0]->sdi[{ch3}][0];"
		  "dlo[{ch3}][1]->sdi[{ch3}][1];"
		  "dlo[{ch4}][0]->sdi[{ch4}][0];"
		  "dlo[{ch4}][1]->sdi[{ch4}][1];"}},
		{UHD4K_ST425_Quad_3Ga_2SI_RGB_Display,
		 {UHD4K_ST425_Quad_3Ga_2SI_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadLink_3Ga},
		  {},
		  true,
		  "fb[{ch1}][2]->tsi[{ch1}][0];"
		  "fb[{ch1}][3]->tsi[{ch1}][1];"

		  "fb[{ch2}][2]->tsi[{ch2}][0];"
		  "fb[{ch2}][3]->tsi[{ch2}][1];"

		  "tsi[{ch1}][2]->dlo[{ch1}][0];"
		  "tsi[{ch1}][3]->dlo[{ch2}][0];"
		  "tsi[{ch2}][2]->dlo[{ch3}][0];"
		  "tsi[{ch2}][3]->dlo[{ch4}][0];"

		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"
		  "dlo[{ch2}][0]->sdi[{ch2}][0];"
		  "dlo[{ch2}][1]->sdi[{ch2}][1];"
		  "dlo[{ch3}][0]->sdi[{ch3}][0];"
		  "dlo[{ch3}][1]->sdi[{ch3}][1];"
		  "dlo[{ch4}][0]->sdi[{ch4}][0];"
		  "dlo[{ch4}][1]->sdi[{ch4}][1];"}},
		{UHD4K_ST425_Quad_3Gb_2SI_RGB_Display,
		 {UHD4K_ST425_Quad_3Gb_2SI_RGB_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadDualLink_3Gb},
		  {},
		  true,
		  "fb[{ch1}][2]->tsi[{ch1}][0];"
		  "fb[{ch1}][3]->tsi[{ch1}][1];"

		  "fb[{ch2}][2]->tsi[{ch2}][0];"
		  "fb[{ch2}][3]->tsi[{ch2}][1];"

		  "tsi[{ch1}][2]->dlo[{ch1}][0];"
		  "tsi[{ch1}][3]->dlo[{ch2}][0];"
		  "tsi[{ch2}][2]->dlo[{ch3}][0];"
		  "tsi[{ch2}][3]->dlo[{ch4}][0];"

		  "dlo[{ch1}][0]->sdi[{ch1}][0];"
		  "dlo[{ch1}][1]->sdi[{ch1}][1];"
		  "dlo[{ch2}][0]->sdi[{ch2}][0];"
		  "dlo[{ch2}][1]->sdi[{ch2}][1];"
		  "dlo[{ch3}][0]->sdi[{ch3}][0];"
		  "dlo[{ch3}][1]->sdi[{ch3}][1];"
		  "dlo[{ch4}][0]->sdi[{ch4}][0];"
		  "dlo[{ch4}][1]->sdi[{ch4}][1];"}},
		/*
		 * SDI YCbCr Capture
		 */
		{AJA_RP_CAP_SDI_SINGLE_SD_HD_YCBCR,
		 {AJA_RP_CAP_SDI_SINGLE_SD_HD_YCBCR,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::SD, RasterDefinition::HD},
		  {VPIDStandard_483_576, VPIDStandard_720, VPIDStandard_1080,
		   VPIDStandard_720_3Ga, VPIDStandard_1080_3Ga},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0]"}},
		{HD_1080_ST372_Dual_YCbCr_Capture,
		 {HD_1080_ST372_Dual_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch2}][0]->fb[{ch2}][0]"}},
		{HD_1080p_ST425_3Gb_DL_YCbCr_Capture,
		 {HD_1080p_ST425_3Gb_DL_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kConvert3GIn,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0]"}},
		{HD_720p_ST425_3Gb_YCbCr_Capture,
		 {HD_720p_ST425_3Gb_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch1}][1]->fb[{ch2}][0];"}},
		{HD_1080p_ST425_3Gb_YCbCr_Capture,
		 {HD_1080p_ST425_3Gb_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_3Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch1}][1]->fb[{ch2}][0];"}},
		{HD_1080p_ST425_Dual_3Ga_YCbCr_Capture,
		 {HD_1080p_ST425_Dual_3Ga_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_Dual_3Ga},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch2}][0]->fb[{ch2}][0];"}},
		{HD_1080p_ST425_Dual_3Gb_YCbCr_Capture,
		 {HD_1080p_ST425_Dual_3Gb_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_Dual_3Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch2}][0]->fb[{ch2}][0];"}},
		{UHD4K_ST292_Quad_1_5_Squares_YCbCr_Capture,
		 {UHD4K_ST292_Quad_1_5_Squares_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch2}][0]->fb[{ch2}][0];"
		  "sdi[{ch3}][0]->fb[{ch3}][0];"
		  "sdi[{ch4}][0]->fb[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Capture,
		 {UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_3Ga},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch2}][0]->fb[{ch2}][0];"
		  "sdi[{ch3}][0]->fb[{ch3}][0];"
		  "sdi[{ch4}][0]->fb[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Capture,
		 {UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KSquares | kConvert3GIn,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"
		  "sdi[{ch2}][0]->fb[{ch2}][0];"
		  "sdi[{ch3}][0]->fb[{ch3}][0];"
		  "sdi[{ch4}][0]->fb[{ch4}][0];"}},
		{UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Capture,
		 {UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_DualLink},
		  {},
		  false,
		  "sdi[{ch1}][0]->tsi[{ch1}][0];"
		  "sdi[{ch1}][1]->tsi[{ch1}][1];"
		  "sdi[{ch2}][0]->tsi[{ch2}][0];"
		  "sdi[{ch2}][1]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		{UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Capture,
		 {UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadLink_3Ga},
		  {},
		  false,
		  "sdi[{ch1}][0]->tsi[{ch1}][0];"
		  "sdi[{ch2}][0]->tsi[{ch1}][1];"
		  "sdi[{ch3}][0]->tsi[{ch2}][0];"
		  "sdi[{ch4}][0]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		{UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Capture,
		 {UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kConvert3GIn | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadDualLink_3Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->tsi[{ch1}][0];"
		  "sdi[{ch2}][0]->tsi[{ch1}][1];"
		  "sdi[{ch3}][0]->tsi[{ch2}][0];"
		  "sdi[{ch4}][0]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		{UHD4K_ST2018_6G_Squares_2SI_YCbCr_Capture,
		 {UHD4K_ST2018_6G_Squares_2SI_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kEnable6GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_6Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"}},
		{UHD4K_ST2018_6G_Squares_2SI_YCbCr_Capture_Kona5_io4KPlus,
		 {UHD4K_ST2018_6G_Squares_2SI_YCbCr_Capture_Kona5_io4KPlus,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable6GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_6Gb},
		  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
		  false,
		  "sdi[{ch1}][0]->tsi[{ch1}][0];"
		  "sdi[{ch2}][0]->tsi[{ch1}][1];"
		  "sdi[{ch3}][0]->tsi[{ch2}][0];"
		  "sdi[{ch4}][0]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		{UHD4K_ST2018_12G_Squares_2SI_YCbCr_Capture,
		 {UHD4K_ST2018_12G_Squares_2SI_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  1,
		  1,
		  kEnable12GOut | kConvert3GaRGBOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_12Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"}},
		{UHD4K_ST2018_12G_Squares_2SI_YCbCr_Capture_Kona5_io4KPlus,
		 {UHD4K_ST2018_12G_Squares_2SI_YCbCr_Capture_Kona5_io4KPlus,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable6GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_12Gb},
		  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
		  false,
		  "sdi[{ch1}][0]->tsi[{ch1}][0];"
		  "sdi[{ch2}][0]->tsi[{ch1}][1];"
		  "sdi[{ch3}][0]->tsi[{ch2}][0];"
		  "sdi[{ch4}][0]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->fb[{ch1}][0];"
		  "tsi[{ch1}][1]->fb[{ch1}][1];"
		  "tsi[{ch2}][0]->fb[{ch2}][0];"
		  "tsi[{ch2}][1]->fb[{ch2}][1];"}},
		// TODO
		{UHD28K_ST2082_Dual_12G_YCbCr_Capture,
		 {UHD28K_ST2082_Dual_12G_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  2,
		  2,
		  kEnable12GOut | kConvert3GaRGBOut | kEnable4KTSI,
		  {RasterDefinition::UHD2_8K},
		  {VPIDStandard_4320_DualLink_12Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"}},
		{UHD28K_ST2082_Quad_12G_YCbCr_Capture,
		 {UHD28K_ST2082_Quad_12G_YCbCr_Capture,
		  ConnectionKind::SDI,
		  NTV2_MODE_CAPTURE,
		  4,
		  4,
		  kEnable12GOut | kConvert3GaRGBOut | kEnable4KTSI,
		  {RasterDefinition::UHD2_8K},
		  {VPIDStandard_4320_QuadLink_12Gb},
		  {},
		  false,
		  "sdi[{ch1}][0]->fb[{ch1}][0];"}},
		/*
		 * SDI YCbCr Display
		 */
		{AJA_RP_OUT_SDI_SINGLE_SD_HD_YCBCR,
		 {AJA_RP_OUT_SDI_SINGLE_SD_HD_YCBCR,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kNoFlags,
		  {RasterDefinition::SD, RasterDefinition::HD},
		  {VPIDStandard_483_576, VPIDStandard_720, VPIDStandard_1080},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"}},
		{HD_1080_ST372_Dual_YCbCr_Display,
		 {HD_1080_ST372_Dual_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  2,
		  2,
		  kNoFlags,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch2}][0]"}},
		{AJA_RP_OUT_SDI_3Ga_HD_YCBCR,
		 {AJA_RP_OUT_SDI_3Ga_HD_YCBCR,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Ga, VPIDStandard_1080_3Ga},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"}},
		{HD_1080p_ST425_3Gb_DL_YCbCr_Display,
		 {HD_1080p_ST425_3Gb_DL_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable3GOut | kConvert3GIn | kConvert3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"}},
		{AJA_RP_OUT_SDI_3GbDS_HD_YCBCR,
		 {AJA_RP_OUT_SDI_3GbDS_HD_YCBCR,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  2,
		  kEnable3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_720_3Gb, VPIDStandard_1080_3Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch1}][1];"}},
		{HD_1080p_ST425_Dual_3Ga_YCbCr_Display,
		 {HD_1080p_ST425_Dual_3Ga_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  2,
		  2,
		  kEnable3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_Dual_3Ga},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch1}][1];"}},
		{HD_1080p_ST425_Dual_3Gb_YCbCr_Display,
		 {HD_1080p_ST425_Dual_3Gb_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  2,
		  2,
		  kEnable3GOut,
		  {RasterDefinition::HD},
		  {VPIDStandard_1080_Dual_3Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch1}][1];"}},
		{UHD4K_ST292_Quad_1_5_Squares_YCbCr_Display,
		 {UHD4K_ST292_Quad_1_5_Squares_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GbOut | kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch2}][0];"
		  "fb[{ch3}][0]->sdi[{ch3}][0];"
		  "fb[{ch4}][0]->sdi[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Display,
		 {UHD4K_ST425_Quad_3Ga_Squares_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kEnable3GbOut,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_3Ga},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch2}][0];"
		  "fb[{ch3}][0]->sdi[{ch3}][0];"
		  "fb[{ch4}][0]->sdi[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Display,
		 {UHD4K_ST425_Quad_3Gb_Squares_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kEnable3GbOut | kEnable4KSquares,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_1080_DualLink_3Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"
		  "fb[{ch2}][0]->sdi[{ch2}][0];"
		  "fb[{ch3}][0]->sdi[{ch3}][0];"
		  "fb[{ch4}][0]->sdi[{ch4}][0];"}},
		{UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Display,
		 {UHD4K_ST425_Dual_3Gb_2SI_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  2,
		  2,
		  kEnable3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_DualLink},
		  {},
		  false,
		  "fb[{ch1}][0]->tsi[{ch1}][0];"
		  "fb[{ch1}][1]->tsi[{ch1}][1];"
		  "fb[{ch2}][0]->tsi[{ch2}][0];"
		  "fb[{ch2}][1]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->sdi[{ch1}][0];"
		  "tsi[{ch1}][1]->sdi[{ch1}][1];"
		  "tsi[{ch2}][0]->sdi[{ch2}][0];"
		  "tsi[{ch2}][1]->sdi[{ch2}][1];"}},
		{UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Display,
		 {UHD4K_ST425_Quad_3Ga_2SI_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadLink_3Ga},
		  {},
		  false,
		  "fb[{ch1}][0]->tsi[{ch1}][0];"
		  "fb[{ch1}][1]->tsi[{ch1}][1];"
		  "fb[{ch2}][0]->tsi[{ch2}][0];"
		  "fb[{ch2}][1]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->sdi[{ch1}][0];"
		  "tsi[{ch1}][1]->sdi[{ch2}][0];"
		  "tsi[{ch2}][0]->sdi[{ch3}][0];"
		  "tsi[{ch2}][1]->sdi[{ch4}][0];"}},
		{UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Display,
		 {UHD4K_ST425_Quad_3Gb_2SI_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable3GOut | kConvert3GaRGBOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_QuadDualLink_3Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->tsi[{ch1}][0];"
		  "fb[{ch1}][1]->tsi[{ch1}][1];"
		  "fb[{ch2}][0]->tsi[{ch2}][0];"
		  "fb[{ch2}][1]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->sdi[{ch1}][0];"
		  "tsi[{ch1}][1]->sdi[{ch2}][0];"
		  "tsi[{ch2}][0]->sdi[{ch3}][0];"
		  "tsi[{ch2}][1]->sdi[{ch4}][0];"}},
		{UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display,
		 {UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable6GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_6Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"}},
		{UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display_Kona5_io4KPlus,
		 {UHD4K_ST2018_6G_Squares_2SI_YCbCr_Display_Kona5_io4KPlus,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable6GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_6Gb},
		  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
		  false,
		  "fb[{ch1}][0]->tsi[{ch1}][0];"
		  "fb[{ch1}][1]->tsi[{ch1}][1];"
		  "fb[{ch2}][0]->tsi[{ch2}][0];"
		  "fb[{ch2}][1]->tsi[{ch2}][1];"
		  "tsi[{ch1}][0]->sdi[{ch1}][0];"
		  "tsi[{ch1}][1]->sdi[{ch2}][0];"
		  "tsi[{ch2}][0]->sdi[{ch3}][0];"
		  "tsi[{ch2}][1]->sdi[{ch4}][0];"}},
		{UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display,
		 {UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  1,
		  1,
		  kEnable12GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_12Gb},
		  {},
		  false,
		  "fb[{ch1}][0]->sdi[{ch1}][0];"}},
		{UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display_Kona5_io4KPlus,
		 {UHD4K_ST2018_12G_Squares_2SI_YCbCr_Display_Kona5_io4KPlus,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable12GOut | kConvert3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD_4K},
		  {VPIDStandard_2160_Single_12Gb},
		  {DEVICE_ID_KONA5, DEVICE_ID_IO4KPLUS},
		  false,
		  "fb[{ch3}][0]->tsi[{ch3}][0];"
		  "fb[{ch3}][1]->tsi[{ch3}][1];"
		  "fb[{ch4}][0]->tsi[{ch4}][0];"
		  "fb[{ch4}][1]->tsi[{ch4}][1];"
		  "tsi[{ch3}][0]->sdi[{ch1}][0];"
		  "tsi[{ch3}][1]->sdi[{ch2}][0];"
		  "tsi[{ch4}][0]->sdi[{ch3}][0];"
		  "tsi[{ch4}][1]->sdi[{ch4}][0];"}},
		// TODO
		{UHD28K_ST2082_Dual_12G_YCbCr_Display,
		 {UHD28K_ST2082_Dual_12G_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  2,
		  2,
		  kEnable12GOut | kConvert3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD2_8K},
		  {VPIDStandard_4320_DualLink_12Gb},
		  {},
		  false,
		  ""}},
		// TODO
		{UHD28K_ST2082_Quad_12G_YCbCr_Display,
		 {UHD28K_ST2082_Quad_12G_YCbCr_Display,
		  ConnectionKind::SDI,
		  NTV2_MODE_DISPLAY,
		  4,
		  4,
		  kEnable12GOut | kConvert3GOut | kEnable4KTSI,
		  {RasterDefinition::UHD2_8K},
		  {VPIDStandard_4320_QuadLink_12Gb},
		  {},
		  false,
		  ""}},
	};
	for (auto &&rp : kRoutingPresets)
		AddPreset(std::move(rp.first), std::move(rp.second));
}

} // namespace aja
